if (is_linux) {
  import("//build/config/linux/pkg_config.gni")

  pkg_config("gio") {
    packages = [ "gio-2.0" ]
  }
}

source_set("credentials") {
  sources = [
    "credential_store.cc",
    "credential_store.h",
    "credential_store_platform.h",
  ]
  public_deps = [ "//base" ]
  deps = []
  if (is_linux) {
    sources += [ "credential_store_linux.cc" ]
    configs += [
      ":gio",
      "//build/config/linux:glib",
    ]
    deps += [ "//third_party/libsecret" ]
  } else if (is_win) {
    sources += [ "credential_store_win.cc" ]
    libs = [ "Advapi32.lib" ]
  }
}
