source_set("prism_ai_ui") {
  sources = [
    "prism_ai_ui.cc",
    "prism_ai_ui.h",
    "resources.h",
  ]
  deps = [
    "//base",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/side_panel:side_panel",
    "//chrome/browser/ui/webui/top_chrome",
    "//chrome/browser/ui/webui:webui_util",
    "//content/public/browser",
    "//prism/ai:chromium",
    "//prism/credentials",
  ]
}
